### ISSUE TITLE
大三下总体规划与安排

### ISSUE THREAD

**Issue by wiku30** [wiku30/myblog#2]
大三下是我在叉院生活中极其重要的一个学期，大部分时间（以及暑假）将在美国UT Austin进行春研。本学期的科研活动将为今年年底申请国外高校起到至关重要的作用，同时由于没有任何课程，科研即为全部任务，这对我的自主学习能力和自我规划能力将是极大的挑战。
因此，在劳逸结合的同时保证学习效率，尽可能发挥自己应有的能力，是这个学期核心目标。
总体计划如下：
0.行动代号：“无问西东”。此规划自2.25至8.31有效。
1.在清华期间，按照40学分（包括旁听）的任务量基准安排学习生活，上课时看paper或完成与科研主题直接相关内容，晚自习时可进行发散性思考或阅读其他（可为本专业其他方面或人文类等）书籍或资料。在美国时按照导师要求学习。
2.由于没有体育课，为保持并提高身体素质，每周保证总共慢跑12km以上的运动量。
3.课余休息尽可能以室外活动，或听音乐会等陶冶情操的活动形式进行。
4.要加强独立自主进行学习探究的精神，同时也要加强与导师和来自世界各地同学的交流，争取在提高学术能力的同时，也能开拓国际视野，结识新朋友。
5.未提到事项维持之前计划不变。

**Comment by Chenyao2333** [comment]
围观点赞

**Comment by crab-baby** [comment]
所以你们也是要上课的呀？

**Comment by wiku30** [comment]
@crab-baby
不用上课...
