### ISSUE TITLE
A glimpse of dreamland

### ISSUE THREAD

**Issue by wiku30** [wiku30/myblog#9]
Note: As long as I am in the US, all texts I write will be in English for potential foreign followers. Also, names appeared in these texts are all pseudonyms, while consistent in all further essays.

注：在我在美国期间，会使用英文写作。同时，所有出现的人名均为化名，但在之后的文字中会保持一致。

**Comment by wiku30** [comment]
When I opened up my eye and saw the exotic view of Austin, it occurred to me that I was already in the US. It seemed that everything changed in a sudden. Although life in the US is not essentially different of that in China, it still felt like a dream, a dream in which everything had just happened in a single week. It is not easy to describe all feelings in a few words, but it was truly different from the routine.

I would have been here five days earlier, but I did choose to let time elapse slower --- for the wish to take a look at the ACM-ICPC World Finals, as well as meet a special friend (#3). Before the departure on 20, though, there are also some preparations to do for my first trip abroad, and all things had to be done on my own, so these days are bound to be busy and unusual.

At first, it is obvious that all costs in the US should be paid in US Dollars, and the money that our institute had given to us was also in USD. However, the convenience of the 21st century made some trouble to me in turn. Considering the inconvenience of exchanging currency, the Airbnb website, as well as my father's credit card, has a default setting to convert all cost to RMB. Ridiculously, it is hard to pay my USD for the impending trip to the US!

Therefore, on 15 and 16, I had to get a international debit card that can save USD, and on the Airbnb website, I tried every means, including changing the language to English, changing my address to somewhere in America and so on, to convince the website that I am the least possible one to be in China, before I could pay my USD out to book my apartment.

**Comment by wiku30** [comment]
As it was my first time to go to the US, even some simplest routines seemed a struggle for me. In my invitation letter, I should have set off on early March, but there happened to be some troubles with getting my materials required for a visa, the schedule had been delayed. It did not affect my research plan much as I could also read papers and think about problems in Beijing, and additionally, it also gained me a chance to see Alicia, which I had always been looking forward to, so although most people think that I was unlucky, I did not think so. Anyway, the visa of a classmate who should go with me was checked, so at least I was not the last one...

Although I delayed my schedule by five days, actually I could not meet her for as long, because the schedule of Finals was pretty tight, especially for her team --- even while other teams went out to visit the Great Wall, they are still practicing for the competition. But anyway, even a glimpse is enough to be exciting, I thought.

The only free activity in the schedule of Finals was in the afternoon of April 18, but on 17, after finishing all preparations of the trip, I decided to take a look to feel the atmosphere in Peking University. When I reached the University Hall, in my sight are dozens of buses entering the venue in succession, and huge crowds of contestants from different countries --- it was much more crowded than I imagined. Soon after I entered Peking University, I received a message from Martin, who was a contestant from Tsinghua, indicating that he saw me. I wonder how I could be easily spotted on the extremely crowded campus...

At the time they began to enter the Hall for the Opening Ceremony, I caught a glimpse of Alicia, who also noticed me in the crowd. Before I came up with the idea to make the way, she came out of the crowd and reached me, talking for a moment before returning to the group and enter the Hall. It seemed that the activity was not open to the public, so I could only take a look around at that point.

Like in last summer, the scene feels as delighting as the dream, but also as familiar as the daily life. Although we did not meet often, it felt that no distance was there at all, just as the initial days in high school despite we did grow up constantly. The everlasting glance and smile, is what persists through years of wear.

**Comment by wiku30** [comment]
"So, see you next time."
"OK, and have a good trip to America!"
"I will be on the flight 48 hours later~"
"~"

After the dreamlike meeting with Alicia, the departure is impending. Moving through long queues in the airport, I stepped on the plane to America. It was a long flight that takes more than 12 hours in total that crosses the ocean. Feeling the motions of engines with eyes closed, it appears to be a rite to welcome a new voyage in my life. It does not mean the end of previous stories of course, but there were truly a lot of brand new challenges to face. Along the flight, my mind was also slowly drifting through the passage of time, towards an unknown continent.

The moment the plane landed, the first glance at the US did not seem too unfamiliar; though, I had to get adapted to new surroundings and prepare for everything that I would need for the stay. The air is clearer, while the sun is thus more burning; The traffic is more fluent, while I still need to take care even when walking on campus; At most times I had to communicate in English, which is both stressing and rewarding...

**Comment by crab-baby** [comment]
I also has similar trouble in foreign currency payment as you. My credit card can only be swiped but there are some restaurants only support card insertion. There are even stores which only allow cash. I have run out of my cash and as I told you, my funding hasn’t received (to my Danske Bank account) yet. It was quite embarrassing when I have to lend from others or paid in RMB instead.
